language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- 3.5-dev
- nightly
before_install:
- pip install pytest pytest-cov
- pip install coveralls
install:
- pip install -r requirements.txt
script:
- py.test -v --tb=short --cov-report=term-missing --cov=halopy tests/
after_success:
- coveralls
before_deploy:
- pip install sphinx
- pip install .
- python setup.py build_sphinx 
deploy:
  provider: pypi
  user: maxpowa
  docs_dir: docs/build/html
  distributions: "sdist bdist_wheel"
  password:
    secure: U2jOIH6MD+ZnseupPuHTtEqz7F5aHKk9QwAQqxLvOmE/joIbOlLpecji7tnmi0R+BEilRs5CJluEhW4adNtMiJ36h4oaZlAf1BHCwanWgWkgoZaFgp7d03sYq81jPudzQsv01JOYK3dN5GBNtuSAZvABlmzWWR7lSijNf3PaCLo2sOR70zbqg3KgEYWAf3hqWWrLBtVmPYHdz2oE9rXcowywWN5Hu8NLohZZJaZyEA+WHp81GVP9Xm8U9z7a9V9PqiepQ/uK32s4Zb4w53qQQYWQbtbXISjgft9+QiJR+3zkh0c1Qlw0Lt2zpjYgA8ampg11fHtBWmeUjrJCBdi7pzgn145Fa3niMU2fR0TiwR0Bsls/YT6Lo7RBbeLhr3nTdAzLWG+V0RfB8mwEQggcbZU728ZYx6S9/CB3wEKzwIFTfa0gFTIbYNQ7Yd9fdTy9Mg5vS4hz7qgDvY5GsUx/jG9n8JgAdjmpNmR3KK4qbuTDzYRDN59kK5nJiIiiaMLRXqJSNNolTWINd2kqXagDAMV/O6lJFxPhxsFx6OjY8OtPviWJFyIW3ZoRmv1nzszb9GXVv7UEGZvHr5yYOesmN9fD+03LPCyh6W9Ugo47sXsG9qC6WbFs5VygeFt26M8LLtY8QwmPqut0DoU2Ij5QdmW6kWTsL1VusdUmHUHKS+c=
  on:
    tags: true
    repo: maxpowa/halopy
